In [1]:
import numpy as np
import statistics as s
from scipy import stats as st

# ans1

## Type of measures of central tendency

There are three type of measures of central tendency.

    1. Mean
    2. Median
    3. mode

# ans2

#### Difference between mean,median,mode

##### Mean

Mean is the average where the sumof all the numbers  is divided
by the total number of numbers.


In [2]:
# for example

arr=np.array([1,2,2,2,3,4,5,6,7,8,9,10,12,100])

In [3]:
arr

array([  1,   2,   2,   2,   3,   4,   5,   6,   7,   8,   9,  10,  12,
       100])

In [4]:
np.mean(arr)

12.214285714285714

### Meadian

The median is the middle value in the list of given numbers
numerically the ordered from smallest to biggest.

In [5]:
# for example

np.median(arr)

5.5

## mode

Mode is the value of the number which occurs most often in the list

In [6]:
s.mode(arr)

2

# ans3

In [7]:
height=np.array([178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5])

In [8]:
height

array([178. , 177. , 176. , 177. , 178.2, 178. , 175. , 179. , 180. ,
       175. , 178.9, 176.2, 177. , 172.5, 178. , 176.5])

# mean

In [9]:
s.mean(height)

177.01875

# median

In [10]:
s.median(height)

177.0

# mode

In [11]:
s.mode(height)

178.0

# ans4

In [12]:
arr=np.array([178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5])

In [13]:
arr

array([178. , 177. , 176. , 177. , 178.2, 178. , 175. , 179. , 180. ,
       175. , 178.9, 176.2, 177. , 172.5, 178. , 176.5])

In [15]:
s.stdev(arr)

1.8472389305844188

# ans5

Measures of dispersion such as range, variance, and standard deviation are used to describe the spread or variability of a dataset. They give an idea of how spread out the data points are from the central tendency.

## Range:
The range is the difference between the maximum and minimum values in a dataset. It gives a rough estimate of the spread of the data. For example, if we have a dataset of test scores with a range of 40, we can say that the scores are spread out over a range of 40 points.

## Variance:
The variance is the average of the squared differences from the mean. It measures how much the data points deviate from the mean. A higher variance indicates a greater spread of the data. For example, if we have a dataset of the heights of students in a class with a variance of 4, we can say that the heights of the students are spread out over a range of 2 cm on either side of the mean.

## Standard deviation:
The standard deviation is the square root of the variance. It measures the spread of the data in the same units as the original data. A higher standard deviation indicates a greater spread of the data. For example, if we have a dataset of the weights of apples in a basket with a standard deviation of 2 kg, we can say that the weights of the apples are spread out over a range of 4 kg on either side of the mean.

## As an example

, consider the following dataset of test scores:

[85, 90, 75, 80, 95, 70, 85, 90, 80, 75]

The mean score is 82, and we can calculate the measures of dispersion as follows:

Range: The range is the difference between the maximum and minimum values, which is 25 (95 - 70). Variance: The variance is the average of the squared differences from the mean, which is 62.5. Standard deviation: The standard deviation is the square root of the variance, which is approximately 7.91.

# ans6

### Venn diagram
is a visual representation of the relationships between sets of data. It is a diagram that shows all possible logical relations between a finite collection of sets, often represented as circles that overlap or are disjoint. Venn diagrams are commonly used to illustrate simple set relationships in logic, statistics, probability, and computer science.

In a Venn diagram, each circle represents a set, and the region where the circles overlap represents the intersection of those sets. The areas outside the circles represent the complement of those sets.

# ans7

In [16]:
A = {2, 3, 4, 5, 6, 7}
B = {0, 2, 6, 8, 10}


In [17]:
intersection=A.intersection(B)

In [18]:
intersection

{2, 6}

In [19]:
union=A.union(B)

In [20]:
union

{0, 2, 3, 4, 5, 6, 7, 8, 10}

# ans8

In statistics, skewness is a measure of the asymmetry of a probability distribution. Skewness refers to the degree to which the data is not symmetrically distributed around the mean. It indicates whether the data is skewed to the left or to the right of the mean.

If a distribution is symmetrical, then it has zero skewness. If the tail of the distribution is longer on the right side than on the left side, then the distribution is said to be positively skewed, and it has a positive skewness. On the other hand, if the tail of the distribution is longer on the left side than on the right side, then the distribution is said to be negatively skewed, and it has a negative skewness.

# ans9

If a data set is right-skewed, it means that the tail of the distribution is longer on the right side, and the data is concentrated on the left side of the distribution. In this case, the mean is greater than the median.

To understand why this is the case, consider a right-skewed distribution like income. In this distribution, there are a small number of individuals who earn very high incomes, which pull the mean to the right. However, most people earn lower incomes, so the median is not as affected by the high earners and remains closer to the center of the distribution.

Therefore, the median will be to the left of the mean in a right-skewed distribution.

# ans10

Covariance and correlation are two statistical measures that are used to quantify the relationship between two variables.

Covariance is a measure of how two variables vary together. It measures the degree to which two variables are linearly related. A positive covariance indicates that the two variables move in the same direction, while a negative covariance indicates that they move in opposite directions. However, the magnitude of covariance does not have a standardized scale and it can be affected by the scale of the variables being measured.

Correlation, on the other hand, is a measure of the strength and direction of the linear relationship between two variables. Correlation ranges from -1 to +1, where -1 indicates a perfect negative correlation, 0 indicates no correlation, and +1 indicates a perfect positive correlation. Correlation is standardized, which means that it is not affected by the scale of the variables being measured.

In statistical analysis, covariance and correlation are used to assess the relationship between two variables. They help to identify patterns and trends in the data, and to determine the strength and direction of the relationship between the variables. They are also used to test hypotheses and to make predictions about the behavior of the variables.

# ans11

The formula for calculating the sample mean is:

Sample Mean = (Sum of all observations) / (Number of observations) In other words, the sample mean is calculated by adding up all the values in a sample and dividing by the number of observations in the sample.

Here is an example calculation:

Suppose we have the following dataset: [4, 7, 9, 12, 15]

To calculate the sample mean, we add up all the values and divide by the number of observations:

Sample Mean = (4 + 7 + 9 + 12 + 15) / 5 = 47 / 5 = 9.4

Therefore, the sample mean for this dataset is 9.4.

# ans12

For a normal distribution, the measures of central tendency, namely the mean, median, and mode, are all equal. In other words, they have the same value.

This is because a normal distribution is a symmetric distribution, with equal amounts of data on both sides of the mean. The median, which is the middle value of the dataset, is also the same as the mean in a normal distribution.

Additionally, the mode, which is the value that occurs most frequently in the dataset, is also equal to the mean and median in a normal distribution.

Therefore, for a normal distribution, the mean, median, and mode are all the same value, and they all represent the center or midpoint of the distribution.

# ans 13

Covariance and correlation are both statistical measures that describe the relationship between two variables, but they differ in several important ways.

Range: The range of covariance is unbounded, which means it can take on any value. In contrast, the range of correlation is between -1 and +1.

Standardization: Covariance is not standardized, which means it is affected by the scale of the variables being measured. Correlation, on the other hand, is standardized, which means it is not affected by the scale of the variables.

Interpretation: Covariance measures the direction and strength of the linear relationship between two variables. A positive covariance indicates a positive relationship between the variables, while a negative covariance indicates a negative relationship. However, it does not provide any information about the strength of the relationship. Correlation, on the other hand, provides information about both the direction and strength of the linear relationship between two variables.

Units: Covariance is measured in units that are the product of the units of the two variables being measured. Correlation is unitless.

# ans 14

Outliers are data points that are significantly different from other observations in a dataset. Outliers can have a significant impact on measures of central tendency and dispersion.

Measures of central tendency, such as the mean, are affected by outliers because they are calculated using all the data points in the dataset. If there are outliers present, they can significantly pull the mean in one direction or another, causing it to be an inaccurate representation of the center of the dataset.

For example, suppose we have the following dataset: [2, 3, 4, 5, 6, 7, 100]. The mean of this dataset is (2+3+4+5+6+7+100) / 7 = 18.43. However, the outlier value of 100 is significantly larger than all the other values in the dataset, which makes the mean an inaccurate representation of the center of the dataset.

Outliers can also affect measures of dispersion, such as the range, variance, and standard deviation. Outliers can increase the range of the dataset, which makes it difficult to interpret the spread of the data. Outliers can also increase the variance and standard deviation, which makes the spread of the data appear larger than it actually is.

For example, suppose we have the following dataset: [2, 3, 4, 5, 6, 7, 100]. The range of this dataset is 98, which makes the spread of the data appear much larger than it actually is. The variance of this dataset is 1372.8, which is also significantly larger than it would be if the outlier were not present.